### PR TITLE
fix(brick): only format arb directory in post_gen hook

### LINKED ISSUE #33: fix: Calling 'mason make r13n' fails when mason templates exist
**Description**
Hello! I'm currently trying to incorporate r13n into an existing project. When I run `mason make r13n --on-conflict overwrite` it fails during the step when it runs `flutter format .` due to the project having existing mason templates. The r13n generated files (app_regionalizations_us.g.dart, etc) are created but the formatting part of it fails. I'm wondering if it's possible for r13n's mason command to make a more localized flutter format call instead?

**Steps To Reproduce**

1. Install mason and make a template (under `project-directory/mason/`)
2. Install r13n and run the `mason make r13n --on-conflict overwrite` command

**Expected Behavior**
The r13n files should be created under `project-directory/lib/r13n/` and flutter formatting should be run on them successfully.

### PR DESCRIPTION
**Pull request by felangel**
## Description

- fix(brick): only format arb directory in post_gen hook (closes #33)

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: bricks/r13n/hooks/post_gen.dart [hunk 1]
```diff
@@ -6,10 +6,11 @@ import 'package:meta/meta.dart';
 
 Future<void> run(HookContext context) async {
   final runProcess = ProcessOverrides.current?.runProcess ?? Process.run;
-  final progress = context.logger.progress('Running "flutter format ."');
+  final arbDir = context.vars['arbDir'] as String;
+  final progress = context.logger.progress('Running "flutter format $arbDir"');
   final result = await runProcess(
     'flutter',
```
Comment (wolfenrain) [inline bricks/r13n/hooks/post_gen.dart:12]: No dart format?

**Review by wolfenrain — APPROVED** [review]

File: bricks/r13n/hooks/post_gen.dart (hunk 1 above)
Comment (felangel) [reply bricks/r13n/hooks/post_gen.dart:12]: haha was trying to keep it simple but you're right...might as well 👍

Comment (felangel) [reply bricks/r13n/hooks/post_gen.dart]: @wolfenrain just updated to use `dart format` 👍

**Review by wolfenrain — APPROVED** [review]
